[package]
name = "blocks_n_stuff"
version = "0.1.0"
edition = "2021"
authors = ["Nils Mathieu <contact@nils-mathieu.fr>"]
description = "A Minecraft-inspired game to showcase my graphics programming skills."
repository = "https://github.com/nils-mathieu/blocks_n_stuff"
license = "MIT"
publish = false

[dependencies]
winit = "0.29"
wgpu = { path = "../wgpu/wgpu" }                     # TODO: use crates.io when wgpu finally uses raw-window-handle v0.6
pollster = "0.3"
glam = { version = "0.24", features = ["bytemuck"] }
bitflags = "2"
bytemuck = { version = "1", features = ["derive"] }

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = "0.52"
features = ["Win32_Foundation"]
